# Generated by Django 5.2.5 on 2025-09-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='News',
        ),
    ]
