# Generated by Django 5.2.6 on 2025-09-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='news_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
